namespace storySprites {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const halloween = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background misc"
    export const halloweenText = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background misc"
    export const holidayText = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const mistletoe = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background misc"
    export const valentinesText = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const holiday = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const holiday2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const birthday = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background misc"
    export const birthdayText = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const world = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const trees = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const field = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const valentines = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const lake = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background misc"
    export const earthdayText = image.ofBuffer(hex``);

}
